import { Poppins } from "next/font/google";
import "./globals.css";

import {ClerkProvider} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/toaster";


const poppins = Poppins({
  weight: ['200', '300','400','500','600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
})


export const metadata = {
  title: "RUPEE API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={poppins.className}>
          
          {children}

          <Toaster />

        </body>
      </html>
    </ClerkProvider>
  )
}
